spring:
  datasource:
    url: jdbc:h2:mem:mydatabase
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG # spring-data still will use JdbcTemplate to execute the queries
