/*
 * This file is generated by jOOQ.
 */
package com.senacor.academy.objpa.jooq;


import com.senacor.academy.objpa.jooq.tables.Customer;
import com.senacor.academy.objpa.jooq.tables.Pizza;
import com.senacor.academy.objpa.jooq.tables.PizzaTopping;
import com.senacor.academy.objpa.jooq.tables.ShopOrder;
import com.senacor.academy.objpa.jooq.tables.ShopOrderItem;
import com.senacor.academy.objpa.jooq.tables.records.CustomerRecord;
import com.senacor.academy.objpa.jooq.tables.records.PizzaRecord;
import com.senacor.academy.objpa.jooq.tables.records.PizzaToppingRecord;
import com.senacor.academy.objpa.jooq.tables.records.ShopOrderItemRecord;
import com.senacor.academy.objpa.jooq.tables.records.ShopOrderRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("CONSTRAINT_5"), new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final UniqueKey<PizzaRecord> CONSTRAINT_4 = Internal.createUniqueKey(Pizza.PIZZA, DSL.name("CONSTRAINT_4"), new TableField[] { Pizza.PIZZA.ID }, true);
    public static final UniqueKey<PizzaToppingRecord> CONSTRAINT_D = Internal.createUniqueKey(PizzaTopping.PIZZA_TOPPING, DSL.name("CONSTRAINT_D"), new TableField[] { PizzaTopping.PIZZA_TOPPING.PIZZA_ID, PizzaTopping.PIZZA_TOPPING.TOPPING }, true);
    public static final UniqueKey<ShopOrderRecord> CONSTRAINT_2 = Internal.createUniqueKey(ShopOrder.SHOP_ORDER, DSL.name("CONSTRAINT_2"), new TableField[] { ShopOrder.SHOP_ORDER.ID }, true);
    public static final UniqueKey<ShopOrderItemRecord> CONSTRAINT_3 = Internal.createUniqueKey(ShopOrderItem.SHOP_ORDER_ITEM, DSL.name("CONSTRAINT_3"), new TableField[] { ShopOrderItem.SHOP_ORDER_ITEM.ID }, true);
    public static final UniqueKey<ShopOrderItemRecord> CONSTRAINT_37 = Internal.createUniqueKey(ShopOrderItem.SHOP_ORDER_ITEM, DSL.name("CONSTRAINT_37"), new TableField[] { ShopOrderItem.SHOP_ORDER_ITEM.SHOP_ORDER_ID, ShopOrderItem.SHOP_ORDER_ITEM.PIZZA_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PizzaToppingRecord, PizzaRecord> FK_PIZZA_TOPPING_PIZZA = Internal.createForeignKey(PizzaTopping.PIZZA_TOPPING, DSL.name("FK_PIZZA_TOPPING_PIZZA"), new TableField[] { PizzaTopping.PIZZA_TOPPING.PIZZA_ID }, Keys.CONSTRAINT_4, new TableField[] { Pizza.PIZZA.ID }, true);
    public static final ForeignKey<ShopOrderRecord, CustomerRecord> FK_SHOP_ORDER_CUSTOMER = Internal.createForeignKey(ShopOrder.SHOP_ORDER, DSL.name("FK_SHOP_ORDER_CUSTOMER"), new TableField[] { ShopOrder.SHOP_ORDER.CUSTOMER_ID }, Keys.CONSTRAINT_5, new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final ForeignKey<ShopOrderItemRecord, PizzaRecord> FK_SHOP_ORDER_ITEM_PIZZA = Internal.createForeignKey(ShopOrderItem.SHOP_ORDER_ITEM, DSL.name("FK_SHOP_ORDER_ITEM_PIZZA"), new TableField[] { ShopOrderItem.SHOP_ORDER_ITEM.PIZZA_ID }, Keys.CONSTRAINT_4, new TableField[] { Pizza.PIZZA.ID }, true);
    public static final ForeignKey<ShopOrderItemRecord, ShopOrderRecord> FK_SHOP_ORDER_ITEM_SHOP_ORDER = Internal.createForeignKey(ShopOrderItem.SHOP_ORDER_ITEM, DSL.name("FK_SHOP_ORDER_ITEM_SHOP_ORDER"), new TableField[] { ShopOrderItem.SHOP_ORDER_ITEM.SHOP_ORDER_ID }, Keys.CONSTRAINT_2, new TableField[] { ShopOrder.SHOP_ORDER.ID }, true);
}
