/*
 * This file is generated by jOOQ.
 */
package com.senacor.academy.objpa.jooq;


import com.senacor.academy.objpa.jooq.tables.Customer;
import com.senacor.academy.objpa.jooq.tables.Pizza;
import com.senacor.academy.objpa.jooq.tables.PizzaTopping;
import com.senacor.academy.objpa.jooq.tables.ShopOrder;
import com.senacor.academy.objpa.jooq.tables.ShopOrderItem;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>PIZZA</code>.
     */
    public static final Pizza PIZZA = Pizza.PIZZA;

    /**
     * The table <code>PIZZA_TOPPING</code>.
     */
    public static final PizzaTopping PIZZA_TOPPING = PizzaTopping.PIZZA_TOPPING;

    /**
     * The table <code>SHOP_ORDER</code>.
     */
    public static final ShopOrder SHOP_ORDER = ShopOrder.SHOP_ORDER;

    /**
     * The table <code>SHOP_ORDER_ITEM</code>.
     */
    public static final ShopOrderItem SHOP_ORDER_ITEM = ShopOrderItem.SHOP_ORDER_ITEM;
}
