spring:
  datasource:
    url: jdbc:h2:mem:mydatabase
  jpa:
    hibernate:
      ddl-auto: none # we use schema.sql + data.sql
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
