CREATE TABLE pizza
(
    id   BIGINT      GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(48) NOT NULL
);

CREATE TABLE pizza_toppings
(
    pizza_id BIGINT      NOT NULL,
    toppings VARCHAR(32) NOT NULL,
    PRIMARY KEY (pizza_id, toppings)
);

CREATE TABLE customer
(
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(32) NOT NULL,
    last_name  VARCHAR(32) NOT NULL
);

CREATE TABLE shop_order
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer (id),
    date        DATE   NOT NULL
);

CREATE TABLE shop_order_item
(
    id            BIGINT   GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    shop_order_id BIGINT   NOT NULL REFERENCES shop_order (id),
    pizza_id      BIGINT   NOT NULL REFERENCES pizza (id),
    amount        INT      NOT NULL,
    UNIQUE (shop_order_id, pizza_id)
);
