/*
 * This file is generated by jOOQ.
 */
package com.senacor.academy.objpa.jooq.tables.records;


import com.senacor.academy.objpa.jooq.tables.PizzaTopping;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PizzaToppingRecord extends UpdatableRecordImpl<PizzaToppingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PIZZA_TOPPING.PIZZA_ID</code>.
     */
    public void setPizzaId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PIZZA_TOPPING.PIZZA_ID</code>.
     */
    public Long getPizzaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PIZZA_TOPPING.TOPPING</code>.
     */
    public void setTopping(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PIZZA_TOPPING.TOPPING</code>.
     */
    public String getTopping() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PizzaToppingRecord
     */
    public PizzaToppingRecord() {
        super(PizzaTopping.PIZZA_TOPPING);
    }

    /**
     * Create a detached, initialised PizzaToppingRecord
     */
    public PizzaToppingRecord(Long pizzaId, String topping) {
        super(PizzaTopping.PIZZA_TOPPING);

        setPizzaId(pizzaId);
        setTopping(topping);
        resetChangedOnNotNull();
    }
}
