/*
 * This file is generated by jOOQ.
 */
package com.senacor.academy.objpa.jooq.tables.records;


import com.senacor.academy.objpa.jooq.tables.ShopOrderItem;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShopOrderItemRecord extends UpdatableRecordImpl<ShopOrderItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHOP_ORDER_ITEM.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHOP_ORDER_ITEM.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SHOP_ORDER_ITEM.SHOP_ORDER_ID</code>.
     */
    public void setShopOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHOP_ORDER_ITEM.SHOP_ORDER_ID</code>.
     */
    public Long getShopOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>SHOP_ORDER_ITEM.PIZZA_ID</code>.
     */
    public void setPizzaId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>SHOP_ORDER_ITEM.PIZZA_ID</code>.
     */
    public Long getPizzaId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>SHOP_ORDER_ITEM.AMOUNT</code>.
     */
    public void setAmount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>SHOP_ORDER_ITEM.AMOUNT</code>.
     */
    public Integer getAmount() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopOrderItemRecord
     */
    public ShopOrderItemRecord() {
        super(ShopOrderItem.SHOP_ORDER_ITEM);
    }

    /**
     * Create a detached, initialised ShopOrderItemRecord
     */
    public ShopOrderItemRecord(Long id, Long shopOrderId, Long pizzaId, Integer amount) {
        super(ShopOrderItem.SHOP_ORDER_ITEM);

        setId(id);
        setShopOrderId(shopOrderId);
        setPizzaId(pizzaId);
        setAmount(amount);
        resetChangedOnNotNull();
    }
}
